package com.devision.subscription.repository;

import com.devision.subscription.model.Subscription;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.util.Optional;

/**
 * ============================================================
 * SUBSCRIPTION REPOSITORY - DATA ACCESS LAYER
 * ============================================================
 *
 * PURPOSE:
 * - MongoDB data access interface for Subscription entities.
 * - Provides Spring Data MongoDB auto-generated query methods.
 * - Enables deterministic subscription lookups by applicant and active state.
 *
 * INHERITS FROM:
 * - MongoRepository<Subscription, String>: CRUD operations + custom queries.
 * Generic params: <Entity, ID Type> = <Subscription, String>.
 *
 * COLLECTIONS MANAGED:
 * - "subscriptions" (defined in Subscription @Document annotation).
 *
 * QUERY METHODS (auto-generated by Spring Data):
 *
 * 1. findByApplicantIdAndIsActiveTrue(applicantId: String)
 * -----------
 * Returns: Optional<Subscription>
 * SQL equivalent: SELECT * FROM subscriptions WHERE applicantId=? AND
 * isActive=true
 * Note: Returns arbitrary active subscription (no ordering; use with caution).
 * Limitation: Does not guarantee latest; prefer
 * findTopByApplicantIdAndIsActiveTrueOrderByStartDateDesc.
 * Use case: Existence check (e.g., "does applicant have any active sub?").
 *
 * 2. findTopByApplicantIdAndIsActiveTrueOrderByStartDateDesc(applicantId:
 * String)
 * -----------
 * Returns: Optional<Subscription>
 * SQL equivalent: SELECT * FROM subscriptions WHERE applicantId=? AND
 * isActive=true
 * ORDER BY startDate DESC LIMIT 1
 * Behavior: Returns most recently activated subscription.
 * Use case: Get current active subscription (deterministic).
 * Used in: getMySubscription(), getCheckoutUrl(), all active-sub lookups.
 *
 * 3. findByApplicantIdAndIsActiveTrueOrderByStartDateDesc(applicantId: String)
 * -----------
 * Returns: List<Subscription>
 * SQL equivalent: SELECT * FROM subscriptions WHERE applicantId=? AND
 * isActive=true
 * ORDER BY startDate DESC
 * Behavior: Returns all active subscriptions ordered by recency.
 * Expected: 0 or 1 results (service enforces single active).
 * Use case: Bulk deactivation before new subscription.
 * Used in: cancelSubscription(), completePayment() (deactivate all existing).
 *
 * DESIGN PATTERNS:
 *
 * - Deterministic queries: Always order by startDate DESC to get latest.
 * - No explicit uniqueness constraint: isActive flag enforces via service
 * logic.
 * - Separation of concerns: Repository is read-only; service handles writes.
 * - Immutability: Once saved, Subscription is queryable; updates via new
 * save().
 *
 * TYPICAL USAGE IN SERVICE:
 * 
 * // Get current subscription
 * Optional<Subscription> active =
 * repo.findTopByApplicantIdAndIsActiveTrueOrderByStartDateDesc(applicantId);
 * 
 * // Deactivate all before creating new
 * List<Subscription> existing =
 * repo.findByApplicantIdAndIsActiveTrueOrderByStartDateDesc(applicantId);
 * existing.forEach(s -> { s.setActive(false); repo.save(s); });
 * 
 * // Create new PREMIUM
 * Subscription premium = new Subscription(...);
 * repo.save(premium);
 *
 * INDEXES (recommended for production):
 * - { applicantId: 1, isActive: 1, startDate: -1 }
 * Covers all three query methods; ensures fast lookups.
 * - Implementation: Create in MongoDB manually or via Mongock/Liquibase.
 *
 * NOTES:
 * - No explicit error handling; Spring Data propagates exceptions.
 * - Query method names follow Spring Data conventions (parsed at runtime).
 * - Optional return type prevents null exceptions; caller uses ifPresent() or
 * orElse().
 * ============================================================
 */
public interface SubscriptionRepository
        extends MongoRepository<Subscription, String> {

    Optional<Subscription> findByApplicantIdAndIsActiveTrue(String applicantId);

    Optional<Subscription> findTopByApplicantIdAndIsActiveTrueOrderByStartDateDesc(String applicantId);

    java.util.List<Subscription> findByApplicantIdAndIsActiveTrueOrderByStartDateDesc(String applicantId);
}
